### ISSUE TITLE
文档显示异常，请使用pre+code包裹代码内容

### ISSUE THREAD

**Issue by zaixia** [prodigytech-doc/api-docs#161]
### 所属页面地址

https://api-docs.ark.online/classes/mw.Navigation.html#findpath

### 选中内容

export default class Example_Navigation_FindPath extends Script {

 protected onStart(): void {
     // 下列逻辑仅在客户端执行
     if(SystemUtil.isClient()) {
         //获取目标对象
         let signs = this.gameObject;
         //获取当前玩家角色
         let myChara = Player.localPlayer.character;

         //添加一个按键方法：按下按键“1”，生成角色寻路轨迹
         InputUtil.onKeyDown(Keys.One, () => {
             let points = Navigation.findPath(myChara.worldTransform.position, signs.worldTransform.position);
             points.forEach((v,i) => {
                 console.error("loc " + v);
                 GameObject.asyncSpawn("84121").then((obj: Model) => {
                     obj.worldTransform.position = v;
                     obj.worldTransform.scale = new Vector(0.2, 0.2, 0.2);
                     obj.setCollision(CollisionStatus.Off);
                 });
             });
         });
     }
 }
}

### 请选择反馈的问题类型

小错误 - 有错别字/语句不通/链接打不开

**Comment by ueking12** [comment]
感谢您的反馈！
我们已经修改好啦，稍后更新页面就可以看到哦
