### ISSUE TITLE
代码显示不全

### ISSUE THREAD

**Issue by zaixia** [prodigytech-doc/api-docs#166]
### 所属页面地址

https://api-docs.ark.online/classes/mwext.GameObjPool.html#clearall

### 选中内容

        for (let i = 0;
i < 10;

### 请选择反馈的问题类型

小错误 - 有错别字/语句不通/链接打不开

**Comment by ueking12** [comment]
感谢您的反馈！
稍后我们会处理哦~
期待您的下次反馈
