### ISSUE TITLE
这一段的格式好像有点问题

### ISSUE THREAD

**Issue by minlo-18** [prodigytech-doc/api-docs#170]
### 所属页面地址

https://api-docs.ark.online/classes/mw.ScreenUtil.html#getgameobjectbyscreenposition

### 选中内容

___

### getSightBeadPosition <Score text="getSightBeadPosition" /> 

• `Static` **getSightBeadPosition**(): [`Vector`](mw.Vector.md) <Badge type="tip" text="client" />

获取相机中心点所瞄准的世界位置

#### Returns

| [`Vector`](mw.Vector.md) | 目标点世界位置 |
| :------ | :------ |

### 请选择反馈的问题类型

小错误 - 有错别字/语句不通/链接打不开

### 补充说明

![image](https://github.com/prodigytech-doc/api-docs/assets/60054647/7408660e-7274-44b3-a7f0-da5f19b579d7)

**Comment by ueking12** [comment]
感谢您的反馈哦！
我们稍后就会修改，期待您的下次反馈！
