### ISSUE TITLE
this.touch.setPlayerController();已无法使用

### ISSUE THREAD

**Issue by minlo-18** [prodigytech-doc/api-docs#172]
### 所属页面地址

https://api-docs.ark.online/classes/mw.SelectionUtil.html#drawgameobjectselectionbox

### 选中内容

setPlayerController
![image](https://github.com/prodigytech-doc/api-docs/assets/60054647/03c272c1-e736-48ca-be68-d6dec5bda39f)

### 请选择反馈的问题类型

小错误 - 有错别字/语句不通/链接打不开

**Comment by ueking12** [comment]
感谢你的反馈！
这个接口我们已经废弃掉了，转而使用另一个InputUtil类中的方法，之后我们会修改027版本示例代码，并在028版本构思写出更好的示例~
希望您持续关注口袋方舟！
