### ISSUE TITLE
方法错误：onPlayerJoin应修改为：onPlayerReconnect、onPlayerDisconnect

### ISSUE THREAD

**Issue by zaixia** [prodigytech-doc/api-docs#174]
### 所属页面地址

https://api-docs.ark.online/classes/mw.Player.html#onplayerjoin

### 选中内容

Player.onPlayerJoin.add((player) => {

### 请选择反馈的问题类型

不准确 - 接口调不通/接口参数错误/接口返回和文档不一致

**Comment by ueking12** [comment]
感谢您细心的发现编辑器文档中出现的问题
稍后我们就会处理哦~
期待您的下次反馈！
