### ISSUE TITLE
我需要一个方法，可以获取所有的子节点用来遍历处理

### ISSUE THREAD

**Issue by zaixia** [prodigytech-doc/api-docs#181]
### 所属页面地址

https://api-docs.ark.online/classes/mw.PanelWidget.html#getchildat

### 选中内容

getChildAt

### 请选择反馈的问题类型

其他

### 补充说明

我需要一个方法，可以获取所有的子节点用来遍历处理

**Comment by ueking12** [comment]
感谢您的反馈！
我们之后UI在030版本会有优化~所有的控件均可挂载子节点，会废弃PanelWidget
关于遍历所有子节点会在周一讨论，商讨如何给出合适的方案！
您的宝贵意见对于我们来说非常有用
希望您持续关注口袋方舟~
