### ISSUE TITLE
registerMGSChatMessageEvent 相关问题

### ISSUE THREAD

**Issue by onionkingdom** [prodigytech-doc/api-docs#201]
### 所属页面地址

https://api-docs.ark.online/classes/mw.RoomService.html#kick

### 选中内容

registerMGSChatMessageEvent 这个返回的 json 字符串结构希望补充一下

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

**Comment by mwking12** [comment]
感谢您的反馈！
稍后我们会详细解释这个接口，补充示例来说明
期待再次提出宝贵的意见，口袋方舟伴你一起成长~
