### ISSUE TITLE
addComponent bInReplicates default参数标识存在歧义

### ISSUE THREAD

**Issue by aaron51514** [prodigytech-doc/api-docs#244]
### 所属页面地址

https://api-docs-031.ark.online/classes/mw.GameObject.html#addcomponent

### 选中内容

是否开启同步
default: false

### 请选择反馈的问题类型

不准确 - 接口调不通/接口参数错误/接口返回和文档不一致

### 补充说明

这里在服务端调用，默认会同步，在客户端调用，默认不同步
const mwNetStatus = (bInReplicates || typeof bInReplicates === "undefined") && IsServer() ? UE37.ENetStatus.ServerAndClient : IsServer() ? UE37.ENetStatus.Server : UE37.ENetStatus.Client;

**Comment by mwking12** [comment]
您好，非常感谢您的反馈，我们这就会进行校对修改，预计在032版本您会看到正确的描述，期待您的再次反馈，感谢
