### ISSUE TITLE
纯读取也有频率限制吗？竞品应该不限纯读取吧？

### ISSUE THREAD

**Issue by honsrx** [prodigytech-doc/api-docs#32]
### 报错的页面地址

https://api-docs.ark.online/modules/DataStorage.DataStorage.html

### 选中内容

获取Get

### 您对所选内容的反馈是？

缺少信息 - 我想了解更多信息

### 其他

纯读取也有频率限制吗？竞品应该不限纯读取吧？

**Comment by minlo-18** [comment]
群里对了一下，频率主要是后端在限制，纯Get也会受到总频率限制的，Roblox也是有的
