### ISSUE TITLE
注释错误

### ISSUE THREAD

**Issue by MyPersimmon** [prodigytech-doc/api-docs#41]
### 报错的页面地址

https://api-docs.ark.online/classes/UI.UIManager.html#showui

### 选中内容

UILayer.UILayerMiddle

### 您对所选内容的反馈是？

小错误 - 有错别字/语句不通/链接打不开

### 其他

应该是UI.UILayerMiddle

**Comment by Metaworld2023** [comment]
已处理，感谢反馈
