### ISSUE TITLE
RouteService下缺失了getGameCarryingData接口

### ISSUE THREAD

**Issue by kaimusala** [prodigytech-doc/api-docs#53]
### 所属页面地址

https://api-docs.ark.online/classes/Service.RouteService.html#table-of-contents

### 选中内容

RouteService 
RouteService下缺失了getGameCarryingData接口

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

**Comment by jiahuipeng** [comment]
你好，这个接口是021版本的需求内容，020版本的编辑器上没有且不应该有。
