### ISSUE TITLE
函数中参数包含要加上的旋转量，未包含当前旋转量，不知是否需要。同类别下包含另一个同名的静态函数，参数需要当前的旋转量，要加上的旋转量，和返回值。

### ISSUE THREAD

**Issue by EKfire** [prodigytech-doc/api-docs#56]
### 所属页面地址

https://api-docs-022.ark.online/classes/Type.Rotation.html#add

### 选中内容

当前旋转量加上一个旋转量

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

函数中参数包含要加上的旋转量，未包含当前旋转量，不知是否需要。同类别下包含另一个同名的静态函数，参数需要当前的旋转量，要加上的旋转量，和返回值。

**Comment by Metaworld2023** [comment]
该Rotation本身的add函数为基于本身的旋转加上入参的旋转，返回值是其实就是当前Rotation加完的结果。
同类别下另一个同名的静态函数需要当前的旋转量，要加上的旋转量，和返回值。
