### ISSUE TITLE
此网页无搜索框

### ISSUE THREAD

**Issue by EKfire** [prodigytech-doc/api-docs#57]
### 所属页面地址

https://api-docs-021.ark.online/

### 选中内容

搜索框

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

021 [口袋方舟 | API (ark.online)](https://api-docs.ark.online/) 这个网址有搜索框，[口袋方舟 | API (ark.online)](https://api-docs-021.ark.online/)这个网址没有搜索框

**Comment by Metaworld2023** [comment]
成本问题，后续使用量上来，会放开搜索
