### ISSUE TITLE
可能这里需要强调一下，角色NPC啥的无法用

### ISSUE THREAD

**Issue by kaimusala** [prodigytech-doc/api-docs#58]
### 所属页面地址

https://api-docs.ark.online/modules/Gameplay.Gameplay.html#onappearancedatachanged

### 选中内容

需要操作的物体

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

**Comment by lyh945** [comment]
我本地验证是能用的，可以试试下面这段代码
Core.GameObject.asyncFind("3492DAF1").then((obj)=>{
		const npc = obj as Gameplay.NPC;
		npc.onMeshChanged.add((guid)=>{
			console.log("npc==guid===="+guid);
		})
		npc.getAppearance<Gameplay.HumanoidV2>().upperCloth.setMesh("71960",false);
	})

**Comment by Metaworld2023** [comment]
022版本支持，请关注后续更新
