### ISSUE TITLE
描述错误“应该为调用端生效”

### ISSUE THREAD

**Issue by dannyli0109** [prodigytech-doc/api-docs#60]
### 所属页面地址

https://api-docs.ark.online/classes/Gameplay.CharacterBase.html#addimpulse

### 选中内容

服务端调用生效

### 请选择反馈的问题类型

不准确 - 接口调不通/接口参数错误/接口返回和文档不一致

### 补充说明

描述为“服务端调用生效”，实际客户端也可以调用

**Comment by Metaworld2023** [comment]
已修正描述内容
