### ISSUE TITLE
命名不符合规范，ID的d应小写

### ISSUE THREAD

**Issue by Exodus820** [prodigytech-doc/api-docs#64]
### 所属页面地址

https://api-docs-022.ark.online/classes/Util.Util.TweenUtil.Tween.html#table-of-contents

### 选中内容

getID

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

改为getId

**Comment by jiahuipeng** [comment]
暂不处理，后续API优化会覆盖现有所有API.
现在的PR和Issue只是针对注释.
