### ISSUE TITLE
为什么不把 

### ISSUE THREAD

**Issue by minlo-18** [prodigytech-doc/api-docs#67]
### 所属页面地址

https://api-docs.ark.online/classes/Service.SoundService.html#play3dsound

### 选中内容

playParam?	any	播放参数: { innerRadius: 内部半径(默认值200), maxDistance: 衰减距离,不包含内部半径(默认值600) } default: {}

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

为什么不做成这样的  play3DSound(resId, target, loopNum?, volume?, innerRadius?,  maxDistance?)
多带个中括号用着很不方便啊。。。 增加使用疑惑性
开发者用的时候觉得不方便还得自己再封一层

**Comment by Metaworld2023** [comment]
已记录，将于新版本补充说明
