### ISSUE TITLE
为什么不把参数直接做到接口里，而是要再封一个参数里面带几个参数？

### ISSUE THREAD

**Issue by minlo-18** [prodigytech-doc/api-docs#68]
### 所属页面地址

https://api-docs.ark.online/classes/Gameplay.GameObject.html#getgameobjectsbyname

### 选中内容

spawnInfo	SpawnInfo	构建物体的信息

### 请选择反馈的问题类型

其他

### 补充说明

为什么不做成这样的 spawnGameObject(assetId, inReplicates?, transform?): GameObject
多带个中括号用着很不方便啊。。。 增加使用疑惑性
开发者用的时候觉得不方便还得自己再封一层

**Comment by Metaworld2023** [comment]
已记录，将于新版本补充说明
