### ISSUE TITLE
接口名问题，Execute拼错了

### ISSUE THREAD

**Issue by Exodus820** [prodigytech-doc/api-docs#69]
### 所属页面地址

https://api-docs.ark.online/classes/Extension.ModuleManager.html#isready

### 选中内容

callExecut

### 请选择反馈的问题类型

不准确 - 接口调不通/接口参数错误/接口返回和文档不一致

### 补充说明

相关接口和注释也需要同步改动

**Comment by shilongybyb** [comment]
已知晓，后续版本修改
