### ISSUE TITLE
注释中false打错了

### ISSUE THREAD

**Issue by Exodus820** [prodigytech-doc/api-docs#70]
### 所属页面地址

https://api-docs.ark.online/classes/Gameplay.NPC.html#servercalculateenable

### 选中内容

true 开启角色计算 flase 关闭角色计算

### 请选择反馈的问题类型

小错误 - 有错别字/语句不通/链接打不开

### 补充说明

注释中false打错了。建议搜索错误拼法，检索一下所有拼写错误处。

**Comment by Metaworld2023** [comment]
已修改
