### ISSUE TITLE
Rotation.add接口需求

### ISSUE THREAD

**Issue by dannyli0109** [prodigytech-doc/api-docs#71]
### 所属页面地址

https://api-docs.ark.online/classes/Type.Rotation.html#add-1

### 选中内容

add
#
• Static add(a, b, outer): Rotation

### 请选择反馈的问题类型

其他

### 补充说明

Rotation.add 最后一个outer参数为必填
而 Vector.add 最后一个outer参数为选填，如果最后一个outer参数为空就会产生一个新的Vector，否则修改传进去的向量
希望把Rotation.add 最后一个outer参数改为选填，跟Vector的用法一样，如果不传outer就会产生一个新的Rotation

**Comment by Metaworld2023** [comment]
该类似问题已在先前反馈中收录，后续版本解决，谢谢反馈~
