### ISSUE TITLE
描述有误

### ISSUE THREAD

**Issue by Aries-MetaApp** [prodigytech-doc/api-docs#86]
### 所属页面地址

https://api-docs.ark.online/groups/Scripting.Scripting.html#addfocuslistener

### 选中内容

只在PIE模式下生效。

### 请选择反馈的问题类型

不准确 - 接口调不通/接口参数错误/接口返回和文档不一致

### 补充说明

应该是「只在PC端生效吧」

**Comment by sst-hue** [comment]
谢谢您的反馈，预计在027优化注释描述，请关注修复
