### ISSUE TITLE
gravityScale中的Precautions注释字段应该放在set中。

### ISSUE THREAD

**Issue by mwking12** [prodigytech-doc/api-docs#91]
### 所属页面地址

https://api-docs.ark.online/classes/Gameplay.CharacterBase.html#forceupdatemovement

### 选中内容

Precautions

范围0~10, 过大和过小的值都会被限制

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

**Comment by ueking12** [comment]
已经修改啦~
