### ISSUE TITLE
注释接口过时

### ISSUE THREAD

**Issue by kaimusala** [prodigytech-doc/api-docs#93]
### 所属页面地址

https://api-docs.ark.online/classes/Gameplay.GameObject.html#asyncfind

### 选中内容

core.setGlobalAsyncOverTime(5000)

现在应该用这个了，Gameplay.setGlobalAsyncTimeout

### 请选择反馈的问题类型

不准确 - 接口调不通/接口参数错误/接口返回和文档不一致

**Comment by ueking12** [comment]
会尽快更改哦~谢谢宝贵意见
