### ISSUE TITLE
core.setGlobalAsyncOverTime(5000);改为Gameplay.setGlobalAsyncTimeout(1000 * 10);

### ISSUE THREAD

**Issue by mwking12** [prodigytech-doc/api-docs#94]
### 所属页面地址

https://api-docs.ark.online/classes/Gameplay.GameObject.html#asyncfind

### 选中内容

 core.setGlobalAsyncOverTime(5000);

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

**Comment by ueking12** [comment]
修改啦~
